### ISSUE TITLE
No md file for info sec

### ISSUE THREAD

**Issue by Chris-webuser** [freeCodeCamp/boilerplate-infosec#20]

**Comment by Chris-webuser** [comment]
Cannot work on the project because there is no information there!

**Comment by ojeytonwilliams** [comment]
Hi @Chris-webuser, could you give us a little more context?  Which page is not working properly?

**Comment by Chris-webuser** [comment]
There are no instructions/user stories in any of the github packages for python projects, actually, in order for us to know what we need to include in these projects. Thanks

**Comment by ojeytonwilliams** [comment]
As I understand it, all the instructions should be in `README.md` inside the repl.it or Collaboratory starter projects.  They all seem to be there, but, in case I missed some, could you link to them here?

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
